forestwork/forestwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('profile/', include('user_profile.urls')),
    path('help/', include('help.urls')),
    path('admin/', admin.site.urls),
]

forestwork/help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('faq', views.FaqListView.as_view(), name='faq'),
]

forestwork/jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.JobListView.as_view(), name='jobs'),
    path('add', views.JobAddView.as_view(), name='job_add'),
    path('<int:pk>', views.JobDetailView.as_view(), name='job'),
    path('<int:pk>/edit', views.JobUpdateView.as_view(), name='job_edit'),
    path('<int:pk>/delete', views.JobDeleteView.as_view(), name='job_delete'),
]

forestwork/jobs/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from settings.models import Country, Specialization


class Job(models.Model):
    STATUS_CHOICES = (
        (0, 'Не активно'),
        (1, 'Активно')
    )

    REMOTE_TYPE_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'На выбор кандидата'),
        (2, 'Только офис'),
        (3, 'Гибридная работа'),
        (4, 'Только удалённо')
    )

    EXP_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'Без опыта работы'),
        (2, '1 год'),
        (3, '2 года'),
        (4, '3 года'),
        (5, '5 лет')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=255, verbose_name='Название вакансии')
    description = models.TextField(verbose_name='Описание')
    specialization = models.ForeignKey(Specialization, null=True, verbose_name='Специализация', on_delete=models.CASCADE)
    country = models.ForeignKey(Country, null=True, verbose_name='Страна', on_delete=models.CASCADE)
    city = models.CharField(blank=True, max_length=255, verbose_name='Город')
    salary = models.IntegerField(blank=True, null=True, verbose_name='Зарплата ($)')
    remote_type = models.IntegerField(blank=True, default=0, choices=REMOTE_TYPE_CHOICES, verbose_name='Удалённая работа / Офис')
    exp = models.IntegerField(blank=True, default=0, choices=EXP_CHOICES, verbose_name='Опыт работы')
    comment = models.TextField(blank=True, verbose_name='Комментарий')
    date_publish = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')
    status = models.IntegerField(blank=True, default=0, choices=STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'jobs'
        verbose_name = 'Вакансию'
        verbose_name_plural = 'Вакансии'
        ordering = ['-date_publish']

forestwork/jobs/forms.py
from django import forms
from .models import Job
from settings.models import Country, Specialization


class JobForm(forms.ModelForm):
    title = forms.CharField(
        label='Название вакансии:',
        required=True,
        help_text='Укажите кого пытаетесь найти. Например: Django Developer на игровой форум.',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите название...'
            }
        )
    )
    description = forms.CharField(
        label='Описание:',
        required=True,
        help_text='Требования к кандидатам, описание проекта, команда, условия работы, пакеты помощи и другая полезная информация.',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание к вакансии...',
                'rows': 5
            }
        )
    )
    specialization = forms.ModelChoiceField(
        label='Специализация:',
        required=False,
        queryset=Specialization.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите специализацию...'
            }
        )
    )
    country = forms.ModelChoiceField(
        label='Страна:',
        required=False,
        queryset=Country.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите страну...'
            }
        )
    )
    city = forms.CharField(
        label='Город:',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Укажите город...'
            }
        )
    )
    salary = forms.IntegerField(
        label='Зарплата:',
        required=False,
        help_text='Учтите, зарплата указывается в долларах.',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    remote_type = forms.ChoiceField(
        label='Удалённая работа / Офис:',
        required=False,
        choices=Job.REMOTE_TYPE_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите тип работы...'
            }
        )
    )
    exp = forms.ChoiceField(
        label='Опыт работы:',
        required=False,
        choices=Job.EXP_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите опыт работы...'
            }
        )
    )
    comment = forms.CharField(
        label='Комментарий:',
        required=False,
        help_text='Укажите дополнительную информацию, которая так или иначе относится к вашему предложению.',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Дополнительная информация...',
                'rows': 5
            }
        )
    )

    class Meta:
        model = Job
        fields = '__all__'
        exclude = ['user']


class JobSearchForm(forms.Form):
    query = forms.CharField(
        label='Поиск:',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите поисковый запрос...'
            }
        )
    )

    class Meta:
        fields = ('query', )

forestwork/jobs/views.py
from django.conf import settings
from .forms import JobForm
from chat.models import Chat
from chat.forms import JobMessageForm
from .models import Job
from .utils import UserCheckTypeEmployerMixin, UserCheckJobAuthorMixin
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin


class JobListView(ListView):
    model = Job
    paginate_by = settings.RESULTS_PER_PAGE
    template_name = 'jobs/index.html'
    context_object_name = 'job_list'
    extra_context = {
        'title': 'Список вакансий',
        'subtitle': 'Доступные вакансии от работодателей'
    }

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        query = self.request.GET.get('query')

        if query:
            return queryset.filter(title__icontains=query, status=1)

        return queryset.filter(status=1)


class JobDetailView(FormMixin, DetailView):
    model = Job
    template_name = 'jobs/job.html'
    context_object_name = 'job'
    form_class = JobMessageForm
    extra_context = {
        'title': 'Название вакансии',
        'subtitle': 'Детальная информация касательно вакансии',
    }

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        chat = Chat.objects.create(
            job=self.object,
            type=1,
            user=self.request.user,
            title=self.object.title,
        )
        chat.members.add(self.request.user, self.object.user)

        form = form.save(commit=False)
        form.user = self.request.user
        form.chat = chat
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('job', kwargs={'pk': self.object.pk})


class JobAddView(LoginRequiredMixin, UserCheckTypeEmployerMixin, SuccessMessageMixin, CreateView):
    model = Job
    form_class = JobForm
    template_name = 'jobs/job_form.html'
    success_message = 'Ваша вакансия была успешно отправлена на проверку. После завершения проверки она станет доступна для просмотра.'
    extra_context = {
        'title': 'Добавление вакансии',
        'subtitle': 'Страница добавления новой вакансии',
    }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class JobUpdateView(LoginRequiredMixin, UserCheckJobAuthorMixin, SuccessMessageMixin, UpdateView):
    model = Job
    form_class = JobForm
    template_name = 'jobs/job_form.html'
    success_message = 'Вы успешно внесли изменения в вакансию.'
    extra_context = {
        'title': 'Редактирование вакансии',
        'subtitle': 'Страница редактирования вакансии',
    }


class JobDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Job
    success_url = '/profile/jobs'
    success_message = 'Вы успешно удалили вакансию.'

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            user=self.request.user
        )

forestwork/templates/jobs/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            {% for job in job_list %}
            <div class="card card-job">
                <h2><a href="{% url 'job' pk=job.id %}">{{ job.title }}</a></h2>
                {% if job.salary %}
                <div class="salary">{{ job.salary }}$</div>
                {% endif %}
                <div class="description mb-3">{{ job.description | truncatewords:30 }}</div>
                <div class="subinfo text-bold text-muted d-flex flex-wrap">
                    <div class="location text-icon">
                    <i class="fi fi-rr-marker"></i>
                    {% if not job.country and not job.city %}
                        Не указано
                    {% else %}
                        {{ job.country }} {{ job.city }}
                    {% endif %}
                    </div>
                    <div class="date_publish text-icon"><i class="fi fi-rr-calendar"></i>{{ job.date_publish }}</div>
                </div>
            </div>
            {% endfor %}
            {% include 'pagination.html' %}
        </div>
        <div class="col-lg-4">
            {% if user.type == 1 %}
            <div class="card">
                <div class="card-heading">
                    <h2>Разместите вакансию</h2>
                </div>
                <p>Самый простой способ найти новых сотрудника — создать вакансию.</p>
                <div>
                    <a class="btn btn-primary btn-with-icon" href="{% url 'job_add' %}"><i class="fi fi-rr-add"></i>Добавить вакансию</a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

forestwork/templates/jobs/job.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ job.title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
        {% if user == job.user %}
            {% if job.status == 0 %}
                <div class="status job-status status-moderate"><i class="fi fi-rr-time-add"></i>Ожидает одобрения</div>
            {% else %}
                <div class="status job-status status-done"><i class="fi fi-rr-check"></i>Активно</div>
            {% endif %}
        {% endif %}
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-job-contact d-flex justify-content-between align-items-center mb-3">
                    <div class="job-contact-info">
                        <div class="avatar avatar-mini">{{ job.user.username|slice:":2" }}</div>
                        <div class="mb-1"><a href="{% url 'employer' pk=job.user.id %}">{{ job.user.name }}</a></div>
                        {% if job.user.website %}
                            <div class="text-muted">{{ job.user.website }}</div>
                        {% else %}
                            <div class="text-muted">{{ job.user.email }}</div>
                        {% endif %}
                    </div>
                    <div>
                        <a href="{% url 'employer' pk=job.user.id %}" class="btn btn-with-icon"><i class="fi fi-rr-user"></i>Профиль работодателя</a>
                        {% if job.user != user and user.type != 1 %}
                        <a href="#job-message" class="btn btn-primary ms-3 btn-with-icon"><i class="fi fi-rr-envelope"></i>Откликнуться</a>
                        {% endif %}
                    </div>
                </div>
                <div class="description">{{ job.description | linebreaks }}</div>
                {% if job.comment %}
                <div class="comment">{{ job.comment }}</div>
                {% endif %}
            </div>
            {% if user.type == 0 %}
            <div class="card" id="job-message">
                <div class="card-heading">
                    <h2>Откликнуться на вакансию</h2>
                    <div class="subtitle">Чтобы откликнуться на вакансию, пожалуйста, заполните форму</div>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.message.auto_id }}" class="form-label">{{ form.message.label }}</label>
                        {{ form.message }}
                        <div class="form-text">{{ form.message.help_text }}</div>
                    </div>
                    {{ form.errors }}
                    <button type="submit" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-envelope"></i>Откликнутся</button>
                </form>
            </div>
            {% endif %}
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-heading">
                    <h2>Дополнительно</h2>
                    <div class="subtitle">Дополнительные сведения, касательно вакансии</div>
                </div>
                <div class="card-salary mb-3">
                    <div class="salary">
                        {% if job.salary %}
                            {{ job.salary }} $
                        {% else %}
                            Не указано
                        {% endif %}
                    </div>
                    <div class="text-muted">Выше указана ожидаемая заработная плата потенциального кандидата в мес.</div>
                </div>
                <ul class="list-group list-menu">
                    {% if job.specialization %}
                    <li class="list-group-item">
                        <span class="text-muted d-block small mb-1">Специализация:</span>
                        <span><i class="fi fi-rr-id-badge"></i>{{ job.specialization }}</span>
                    </li>
                    {% endif %}
                    {% if job.country or job.city %}
                    <li class="list-group-item">
                        <span class="text-muted d-block small mb-1">Местоположение:</span>
                        <span><i class="fi fi-rr-marker"></i>{{ job.country }} {{ job.city }}</span>
                    </li>
                    {% endif %}
                    {% if job.exp %}
                    <li class="list-group-item">
                        <span class="text-muted d-block small mb-1">Опыт работы:</span>
                        <span><i class="fi fi-rr-user-time"></i>{{ job.get_exp_display }}</span>
                    </li>
                    {% endif %}
                    {% if job.remote_type %}
                    <li class="list-group-item">
                        <span class="text-muted d-block small mb-1">Тип работы:</span>
                        <span><i class="fi fi-rr-city"></i>{{ job.get_remote_type_display }}</span>
                    </li>
                    {% endif %}
                    <li class="list-group-item">
                        <span class="text-muted d-block small mb-1">Дата публикации:</span>
                        <span><i class="fi fi-rr-calendar-lines-pen"></i>{{ job.date_publish }}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

forestwork/templates/jobs/job_add.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-8">
            <div class="card">
                <div class="card-heading">
                    <h2>Добавить вакансию</h2>
                    <div class="subtitle">Чтобы добавить вакансию заполните форму нижу</div>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.title.auto_id }}" class="form-label">{{ form.title.label }}</label>
                        {{ form.title }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.description.auto_id }}" class="form-label">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.country.auto_id }}" class="form-label">{{ form.country.label }}</label>
                                {{ form.country }}
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.city.auto_id }}" class="form-label">{{ form.city.label }}</label>
                                {{ form.city }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="mb-3">
                                <label for="{{ form.salary.auto_id }}" class="form-label">{{ form.salary.label }}</label>
                                {{ form.salary }}
                                <div class="form-text">{{ form.salary.help_text }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.comment.auto_id }}" class="form-label">{{ form.comment.label }}</label>
                        {{ form.comment }}
                        <div class="form-text">{{ form.comment.help_text }}</div>
                    </div>
                    <button type="submit" class="btn btn-primary">Добавить вакансию</button>
                </form>
            </div>
        </div>
        <div class="col-4">

        </div>
    </div>
</div>
{% endblock content %}

forestwork/templates/jobs/job_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-heading">
                    <h2>Добавить вакансию</h2>
                    <div class="subtitle">Чтобы добавить вакансию заполните форму нижу</div>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="{{ form.title.auto_id }}" class="form-label">{{ form.title.label }}</label>
                        {{ form.title }}
                        <div class="form-text">{{ form.title.help_text }}</div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.description.auto_id }}" class="form-label">{{ form.description.label }}</label>
                        {{ form.description }}
                        <div class="form-text">{{ form.description.help_text }}</div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.specialization.auto_id }}" class="form-label">{{ form.specialization.label }}</label>
                        {{ form.specialization }}
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.country.auto_id }}" class="form-label">{{ form.country.label }}</label>
                                {{ form.country }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.city.auto_id }}" class="form-label">{{ form.city.label }}</label>
                                {{ form.city }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label for="{{ form.salary.auto_id }}" class="form-label">{{ form.salary.label }}</label>
                                {{ form.salary }}
                                <div class="form-text">{{ form.salary.help_text }}</div>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.remote_type.auto_id }}" class="form-label">{{ form.remote_type.label }}</label>
                        {{ form.remote_type }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.exp.auto_id }}" class="form-label">{{ form.exp.label }}</label>
                        {{ form.exp }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.comment.auto_id }}" class="form-label">{{ form.comment.label }}</label>
                        {{ form.comment }}
                        <div class="form-text">{{ form.comment.help_text }}</div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-add"></i>Добавить вакансию</button>
                </form>
            </div>
        </div>
        <div class="col-lg-4">

        </div>
    </div>
</div>
{% endblock content %}