forestwork/forestwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('profile/', include('user_profile.urls')),
    path('help/', include('help.urls')),
    path('admin/', admin.site.urls),
]

forestwork/help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('faq', views.FaqListView.as_view(), name='faq'),
]

forestwork/jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.JobListView.as_view(), name='jobs'),
    path('add', views.JobAddView.as_view(), name='job_add'),
    path('<int:pk>', views.JobDetailView.as_view(), name='job'),
    path('<int:pk>/edit', views.JobUpdateView.as_view(), name='job_edit'),
    path('<int:pk>/delete', views.JobDeleteView.as_view(), name='job_delete'),
]

forestwork/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

forestwork/chat/models.py
from django.db import models
from jobs.models import Job
from django.conf import settings


class Chat(models.Model):
    TYPE_CHOICES = (
        (0, 'Предложение'),
        (1, 'Отклик на вакансию')
    )
    title = models.CharField(max_length=255, verbose_name='Заголовок чата')
    job = models.ForeignKey(Job, null=True, verbose_name='Вакансия', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user', null=False, verbose_name='Инициатор чата', on_delete=models.CASCADE)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL)
    type = models.IntegerField(blank=True, default=0, choices=TYPE_CHOICES, verbose_name='Тип диалога')
    date_publish = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'chats'
        verbose_name = 'Чат'
        verbose_name_plural = 'Чаты'
        ordering = ['date_publish']


# Create your models here.
class Message(models.Model):
    chat = models.ForeignKey(Chat, null=True, verbose_name='Чат', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, related_name='sender_user', verbose_name='Отправитель', on_delete=models.CASCADE)
    message = models.TextField(verbose_name='Сообщение')
    date_publish = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        db_table = 'messages'
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['date_publish']

forestwork/jobs/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from settings.models import Country, Specialization


class Job(models.Model):
    STATUS_CHOICES = (
        (0, 'Не активно'),
        (1, 'Активно')
    )

    REMOTE_TYPE_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'На выбор кандидата'),
        (2, 'Только офис'),
        (3, 'Гибридная работа'),
        (4, 'Только удалённо')
    )

    EXP_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'Без опыта работы'),
        (2, '1 год'),
        (3, '2 года'),
        (4, '3 года'),
        (5, '5 лет')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=255, verbose_name='Название вакансии')
    description = models.TextField(verbose_name='Описание')
    specialization = models.ForeignKey(Specialization, null=True, verbose_name='Специализация', on_delete=models.CASCADE)
    country = models.ForeignKey(Country, null=True, verbose_name='Страна', on_delete=models.CASCADE)
    city = models.CharField(blank=True, max_length=255, verbose_name='Город')
    salary = models.IntegerField(blank=True, null=True, verbose_name='Зарплата ($)')
    remote_type = models.IntegerField(blank=True, default=0, choices=REMOTE_TYPE_CHOICES, verbose_name='Удалённая работа / Офис')
    exp = models.IntegerField(blank=True, default=0, choices=EXP_CHOICES, verbose_name='Опыт работы')
    comment = models.TextField(blank=True, verbose_name='Комментарий')
    date_publish = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')
    status = models.IntegerField(blank=True, default=0, choices=STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'jobs'
        verbose_name = 'Вакансию'
        verbose_name_plural = 'Вакансии'
        ordering = ['-date_publish']

forestwork/main/models.py
from django.db import models

# Create your models here.

forestwork/chat/forms.py
from django import forms
from .models import Message
from jobs.models import Job


class JobMessageForm(forms.ModelForm):
    message = forms.CharField(
        label='Текст сообщения:',
        required=True,
        help_text='Укажите свои сильные стороны, навыки и почему именно вы являетесь хорошим кандидатом',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст сообщения...',
                'rows': 5
            }
        )
    )

    class Meta:
        model = Message
        fields = ['message', ]


class AnswerChatForm(forms.ModelForm):
    message = forms.CharField(
        required=True,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст сообщения...',
                'rows': 1
            }
        )
    )

    class Meta:
        model = Message
        fields = ['message', ]


class JobOfferForm(forms.ModelForm):
    def __init__(self, current_user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['job'].queryset = Job.objects.filter(user=current_user, status=1)

    job = forms.ModelChoiceField(
        label='Вакансия:',
        queryset=None,
        required=True,
        help_text='Выберите вакансию которую хотите предложить кандидату',
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Выберите вакансию...',
            }
        )
    )
    message = forms.CharField(
        label='Текст сообщения:',
        required=True,
        help_text='Укажите основную информацию касательно вакансии или работы которую предлагаете.',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст сообщения...',
                'rows': 5
            }
        )
    )

    class Meta:
        model = Message
        fields = ['message', 'job']

forestwork/jobs/forms.py
from django import forms
from .models import Job
from settings.models import Country, Specialization


class JobForm(forms.ModelForm):
    title = forms.CharField(
        label='Название вакансии:',
        required=True,
        help_text='Укажите кого пытаетесь найти. Например: Django Developer на игровой форум.',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите название...'
            }
        )
    )
    description = forms.CharField(
        label='Описание:',
        required=True,
        help_text='Требования к кандидатам, описание проекта, команда, условия работы, пакеты помощи и другая полезная информация.',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание к вакансии...',
                'rows': 5
            }
        )
    )
    specialization = forms.ModelChoiceField(
        label='Специализация:',
        required=False,
        queryset=Specialization.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите специализацию...'
            }
        )
    )
    country = forms.ModelChoiceField(
        label='Страна:',
        required=False,
        queryset=Country.objects.all(),
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите страну...'
            }
        )
    )
    city = forms.CharField(
        label='Город:',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Укажите город...'
            }
        )
    )
    salary = forms.IntegerField(
        label='Зарплата:',
        required=False,
        help_text='Учтите, зарплата указывается в долларах.',
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    remote_type = forms.ChoiceField(
        label='Удалённая работа / Офис:',
        required=False,
        choices=Job.REMOTE_TYPE_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите тип работы...'
            }
        )
    )
    exp = forms.ChoiceField(
        label='Опыт работы:',
        required=False,
        choices=Job.EXP_CHOICES,
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': 'Укажите опыт работы...'
            }
        )
    )
    comment = forms.CharField(
        label='Комментарий:',
        required=False,
        help_text='Укажите дополнительную информацию, которая так или иначе относится к вашему предложению.',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Дополнительная информация...',
                'rows': 5
            }
        )
    )

    class Meta:
        model = Job
        fields = '__all__'
        exclude = ['user']


class JobSearchForm(forms.Form):
    query = forms.CharField(
        label='Поиск:',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Введите поисковый запрос...'
            }
        )
    )

    class Meta:
        fields = ('query', )

forestwork/chat/views.py
from django.shortcuts import render

# Create your views here.

forestwork/jobs/views.py
from django.conf import settings
from .forms import JobForm
from chat.models import Chat
from chat.forms import JobMessageForm
from .models import Job
from .utils import UserCheckTypeEmployerMixin, UserCheckJobAuthorMixin
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin


class JobListView(ListView):
    model = Job
    paginate_by = settings.RESULTS_PER_PAGE
    template_name = 'jobs/index.html'
    context_object_name = 'job_list'
    extra_context = {
        'title': 'Список вакансий',
        'subtitle': 'Доступные вакансии от работодателей'
    }

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        query = self.request.GET.get('query')

        if query:
            return queryset.filter(title__icontains=query, status=1)

        return queryset.filter(status=1)


class JobDetailView(FormMixin, DetailView):
    model = Job
    template_name = 'jobs/job.html'
    context_object_name = 'job'
    form_class = JobMessageForm
    extra_context = {
        'title': 'Название вакансии',
        'subtitle': 'Детальная информация касательно вакансии',
    }

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        chat = Chat.objects.create(
            job=self.object,
            type=1,
            user=self.request.user,
            title=self.object.title,
        )
        chat.members.add(self.request.user, self.object.user)

        form = form.save(commit=False)
        form.user = self.request.user
        form.chat = chat
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('job', kwargs={'pk': self.object.pk})


class JobAddView(LoginRequiredMixin, UserCheckTypeEmployerMixin, SuccessMessageMixin, CreateView):
    model = Job
    form_class = JobForm
    template_name = 'jobs/job_form.html'
    success_message = 'Ваша вакансия была успешно отправлена на проверку. После завершения проверки она станет доступна для просмотра.'
    extra_context = {
        'title': 'Добавление вакансии',
        'subtitle': 'Страница добавления новой вакансии',
    }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class JobUpdateView(LoginRequiredMixin, UserCheckJobAuthorMixin, SuccessMessageMixin, UpdateView):
    model = Job
    form_class = JobForm
    template_name = 'jobs/job_form.html'
    success_message = 'Вы успешно внесли изменения в вакансию.'
    extra_context = {
        'title': 'Редактирование вакансии',
        'subtitle': 'Страница редактирования вакансии',
    }


class JobDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Job
    success_url = '/profile/jobs'
    success_message = 'Вы успешно удалили вакансию.'

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(
            user=self.request.user
        )

forestwork/main/views.py
from django.views.generic import TemplateView
from django.views.generic.edit import FormMixin
from jobs.models import Job
from jobs.forms import JobSearchForm
from users.models import User


# Create your views here.
class IndexView(FormMixin, TemplateView):
    template_name = 'main/index.html'
    form_class = JobSearchForm
    extra_context = {
        'title': 'ForestWork',
        'subtitle': 'Сервис поиска работы и кандидатов'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job_list'] = Job.objects.filter(status=1)[:5]
        context['employer_list'] = User.objects.filter(type=1)[:5]
        context['developer_list'] = User.objects.filter(type=0)[:5]
        context['job_count'] = Job.objects.all().count()
        return context

forestwork/templates/profile/chat.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div id="chat" class="card">
                <div class="card-heading d-flex justify-content-between align-items-center">
                    <div>
                        <h2>{{ chat.title }}</h2>
                        <div class="subtitle">Открытый диалог с пользователем</div>
                    </div>
                    <div>
                        {% if chat.type == 1 %}
                        <a href="{% url 'job' pk=chat.job.id %}" class="btn btn-with-icon"><i class="fi fi-rr-briefcase"></i>Смотреть вакансию</a>
                        {% endif %}
                        {% if chat.user.type == 1 %}
                        <a href="{% url 'employer' pk=chat.user.id %}" class="btn btn-icon btn-with-icon"><i class="fi fi-rr-user"></i></a>
                        {% else %}
                        <a href="{% url 'developer' pk=chat.user.id %}" class="btn btn-icon btn-with-icon"><i class="fi fi-rr-user"></i></a>
                        {% endif %}
                        <button type="button" class="btn btn-icon btn-with-icon btn-delete-message" data-bs-toggle="modal" data-bs-target="#delete-message"><i class="fi fi-rr-trash"></i></button>
                    </div>
                </div>
                <div class="chat-body">
                    <div class="chat-heading text-center">
                        <span class="icon"><i class="fi fi-rr-comment"></i></span>
                        <div class="mb-2">
                            Пользователь
                            {% if chat.user.type == 0 %}
                                <a href="{% url 'developer' pk=chat.user.id %}">{{ chat.user.username }}</a>
                            {% else %}
                                <a href="{% url 'employer' pk=chat.user.id %}">{{ chat.user.username }}</a>
                            {% endif %}
                            начал новый чат.</div>
                        <div class="text-muted small">
                            <span><i class="fi fi-rr-calendar me-1"></i>Дата создания чата: {{ chat.date_publish }}</span>
                            <span class="ms-3"><i class="fi fi-rr-tags me-1"></i>Тип диалога: {{ chat.get_type_display }}</span>
                        </div>

                    </div>
                    {% for message in chat_messages %}
                    <div class="row message-row {% if message.user == user %}justify-content-end chat-right{% endif %}">
                        <div class="col-lg-7">
                            <div class="chat-message mb-3">
                                <div class="avatar avatar-mini">{{ message.user.username|slice:":2" }}</div>
                                <div class="chat-text mb-1">
                                    <div class="text">{{ message.message }}</div>
                                </div>
                                <div class="text-muted small">
                                    {{ message.date_publish }}
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-9 mb-sm-3 mb-md-0">
                            {{ form.message }}
                        </div>
                        <div class="col-md-3">
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-envelope"></i>Отправить</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'profile/menu.html' %}
        </div>
    </div>
</div>
<div class="modal fade" id="delete-message" tabindex="-1" aria-labelledby="delete-vacancy-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5">{{ chat.title }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Данная операция приведет к удалению чата без возможности восстановления. Подтвердите это действие.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
          <form method="post" action="{% url 'profile_chat_delete' pk=chat.id %}">
              {% csrf_token %}
              <button type="submit" class="btn">Подтвердить</button>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

forestwork/templates/profile/chats.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-heading">
                    <h2>Открытые диалоги</h2>
                    <div class="subtitle">Список отправленных и полученных сообщений</div>
                </div>
                <table id="table-message" class="display">
                    <thead>
                        <tr>
                            <th>Дата</th>
                            <th>Название</th>
                            <th>Тип диалога</th>
                            <th>Сообщение</th>
                            <th>Действие</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for chat in chats %}
                    <tr>
                        <td>{{ chat.date_publish }}</td>
                        <td>{{ chat.title }}</td>
                        <td>{{ chat.get_type_display }}</td>
                        <td>
                            <a href="{% url 'profile_chat' pk=chat.id %}">{{ chat.message_set.last.user }}</a>
                            <div class="text-muted small">{{ chat.message_set.last.message | truncatewords:10}}</div>
                        </td>
                        <td style="white-space: nowrap"><a href="{% url 'profile_chat' pk=chat.id %}" class="btn btn-with-icon"><i class="fi fi-rr-envelope-open"></i>Читать</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'profile/menu.html' %}
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
<script>
$('#table-message').DataTable({
    searching: false,
    paging: false,
    info: false
});
</script>
{% endblock scripts %}

forestwork/templates/profile/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="user-profile">
                    <div class="avatar">{{ user.username|slice:"2" }}</div>
                    <div class="name">{{ user.name }}</div>
                    <div class="location text-muted">
                        <i class="fi fi-rr-marker"></i>
                        {% if not user.country and not user.city %}
                            Не указано
                        {% else %}
                            {{ user.country }} {{ user.city }}
                        {% endif %}
                    </div>
                    <div class="date text-muted mt-3">Последняя активность: {{ user.last_login  }}</div>
                    <div class="date text-muted">На сервисе с: {{ user.date_joined }}</div>

                </div>
            </div>
            <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link btn btn-with-icon active" id="pills-about-tab" data-bs-toggle="pill" data-bs-target="#pills-about" type="button" role="tab" aria-controls="pills-about" aria-selected="true">
                        <i class="fi fi-rr-id-badge"></i>
                        Обо мне
                    </button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link btn btn-with-icon" id="pills-contacts-tab" data-bs-toggle="pill" data-bs-target="#pills-contacts" type="button" role="tab" aria-controls="pills-contacts" aria-selected="false"><i class="fi fi-rr-at"></i>Контакты</button>
                </li>
            </ul>
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-about" role="tabpanel" aria-labelledby="pills-about-tab" tabindex="0">
                    {% if user.type == 0 %}
                    <div class="card">
                        <div class="card-heading">
                            <h2>Специализация и опыт работы</h2>
                            <div class="subtitle">Информация касательно направления и опыта работы</div>
                        </div>
                        {% if user.exp or user.specialization %}
                        <ul class="list-unstyled list-contacts mb-0">
                            {% if user.exp %}
                            <li><span class="left">Опыт работы:</span><span class="right">{{ user.get_exp_display }}</span></li>
                            {% endif %}
                            {% if user.specialization %}
                            <li><span class="left">Специализация:</span><span class="right">{{ user.specialization }}</span></li>
                            {% endif %}
                        </ul>
                        {% else %}
                        Пользователь не указал данную информацию
                        {% endif %}
                    </div>
                    {% endif %}
                    {% if user.about %}
                    <div class="card">
                        <div class="card-heading">
                            <h2>Обо мне</h2>
                            <div class="subtitle">Дополнительная информация</div>
                        </div>
                        {{ user.about | linebreaks }}
                    </div>
                    {% endif %}
                </div>
                <div class="tab-pane fade" id="pills-contacts" role="tabpanel" aria-labelledby="pills-contacts-tab" tabindex="0">
                    <div class="card">
                        <div class="card-heading">
                            <h2>Контактная информация</h2>
                            <div class="subtitle">Список доступных контактов пользователя</div>
                        </div>
                        <ul class="list-unstyled list-contacts mb-0">
                            {% if user.phone %}
                            <li><span class="left">Телефон:</span><span class="right"><a href="tel:{{ user.phone }}">{{ user.phone }}</a></span></li>
                            {% endif %}
                            {% if user.email %}
                            <li><span class="left">E-mail:</span><span class="right"><a href="mailto:{{ user.email }}">{{ user.email }}</a></span></li>
                            {% endif %}
                            {% if user.telegram %}
                            <li><span class="left">Telegram:</span><span class="right">{{ user.telegram }}</span></li>
                            {% endif %}
                            {% if user.whatsapp %}
                            <li><span class="left">Whatsapp:</span><span class="right">{{ user.whatsapp }}</span></li>
                            {% endif %}
                            {% if user.linkedin %}
                            <li><span class="left">LinkedIn:</span><span class="right"><a href="{{ user.linkedin }}">{{ user.linkedin }}</a></span></li>
                            {% endif %}
                            {% if user.github %}
                            <li><span class="left">GitHub:</span><span class="right"><a href="{{ user.github }}">{{ user.github }}</a></span></li>
                            {% endif %}
                            {% if user.website %}
                            <li><span class="left">Веб-сайт:</span><span class="right"><a href="{{ user.website }}">{{ user.website }}</a></span></li>
                            {% endif %}
                            {% if user.portfolio %}
                            <li><span class="left">Портфолио:</span><span class="right"><a href="{{ user.portfolio }}">{{ user.portfolio }}</a></span></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'profile/menu.html' %}
        </div>
    </div>
</div>
{% endblock content %}

forestwork/templates/profile/menu.html
<div class="card">
    <div class="card-heading">
        <h2>Меню пользователя</h2>
        <div class="subtitle">Навигация пользователя</div>
    </div>
    <ul class="list-group list-menu">
        <li class="list-group-item"><a href="{% url 'profile' %}"><i class="fi fi-rr-user"></i>Мой профиль</a></li>
        <li class="list-group-item"><a href="{% url 'profile_chats' %}"><i class="fi fi-rr-envelope"></i>Мои сообщения</a></li>
        {% if user.type == 1 %}
        <li class="list-group-item"><a href="{% url 'profile_jobs' %}"><i class="fi fi-rr-briefcase"></i>Мои вакансии</a></li>
        <li class="list-group-item"><a href="{% url 'job_add' %}"><i class="fi fi-rr-add"></i>Добавить вакансию</a></li>
        {% endif %}
        <li class="list-group-item"><a href="{% url 'profile_main' %}"><i class="fi fi-rr-document"></i>Общее</a></li>
        {% if user.type == 0 %}
        <li class="list-group-item"><a href="{% url 'profile_specializations' %}"><i class="fi fi-rr-e-learning"></i>Специализация</a></li>
        {% endif %}
        <li class="list-group-item"><a href="{% url 'profile_contacts' %}"><i class="fi fi-rr-at"></i>Контактные данные</a></li>
        <li class="list-group-item"><a href="{% url 'profile_password' %}"><i class="fi fi-rr-lock"></i>Сменить пароль</a></li>
        <li class="list-group-item"><a href="{% url 'logout' %}"><i class="fi fi-rr-sign-out-alt"></i>Выйти</a></li>
    </ul>
</div>

forestwork/templates/profile/messages.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="header">
        <h1>{{ title }}</h1>
        <div class="subtitle">{{ subtitle }}</div>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-heading">
                    <h2>Открытые диалоги</h2>
                    <div class="subtitle">Список отправленных и полученных сообщений</div>
                </div>
                <table id="table-message" class="display">
                    <thead>
                        <tr>
                            <th>Дата</th>
                            <th>Название</th>
                            <th>Тип диалога</th>
                            <th>Сообщение</th>
                            <th>Действие</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for chat in chats %}
                    <tr>
                        <td>{{ chat.date_publish }}</td>
                        <td>{{ chat.title }}</td>
                        <td>{{ chat.get_type_display }}</td>
                        <td>
                            <a href="{% url 'profile_message' pk=chat.id %}">{{ chat.message_set.last.user }}</a>
                            <div class="text-muted small">{{ chat.message_set.last.message | truncatewords:10}}</div>
                        </td>
                        <td style="white-space: nowrap"><a href="{% url 'profile_message' pk=chat.id %}" class="btn btn-with-icon"><i class="fi fi-rr-envelope-open"></i>Читать</a></td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'profile/menu.html' %}
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
<script>
$('#table-message').DataTable({
    searching: false,
    paging: false,
    info: false
});
</script>
{% endblock scripts %}