forestwork/forestwork/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('jobs/', include('jobs.urls')),
    path('users/', include('users.urls')),
    path('profile/', include('user_profile.urls')),
    path('help/', include('help.urls')),
    path('admin/', admin.site.urls),
]

forestwork/help/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('faq', views.FaqListView.as_view(), name='faq'),
]

forestwork/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

forestwork/jobs/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from settings.models import Country, Specialization


class Job(models.Model):
    STATUS_CHOICES = (
        (0, 'Не активно'),
        (1, 'Активно')
    )

    REMOTE_TYPE_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'На выбор кандидата'),
        (2, 'Только офис'),
        (3, 'Гибридная работа'),
        (4, 'Только удалённо')
    )

    EXP_CHOICES = (
        (0, 'Не выбрано'),
        (1, 'Без опыта работы'),
        (2, '1 год'),
        (3, '2 года'),
        (4, '3 года'),
        (5, '5 лет')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=255, verbose_name='Название вакансии')
    description = models.TextField(verbose_name='Описание')
    specialization = models.ForeignKey(Specialization, null=True, verbose_name='Специализация', on_delete=models.CASCADE)
    country = models.ForeignKey(Country, null=True, verbose_name='Страна', on_delete=models.CASCADE)
    city = models.CharField(blank=True, max_length=255, verbose_name='Город')
    salary = models.IntegerField(blank=True, null=True, verbose_name='Зарплата ($)')
    remote_type = models.IntegerField(blank=True, default=0, choices=REMOTE_TYPE_CHOICES, verbose_name='Удалённая работа / Офис')
    exp = models.IntegerField(blank=True, default=0, choices=EXP_CHOICES, verbose_name='Опыт работы')
    comment = models.TextField(blank=True, verbose_name='Комментарий')
    date_publish = models.DateTimeField(auto_now=True, verbose_name='Дата публикации')
    status = models.IntegerField(blank=True, default=0, choices=STATUS_CHOICES, verbose_name='Статус')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'jobs'
        verbose_name = 'Вакансию'
        verbose_name_plural = 'Вакансии'
        ordering = ['-date_publish']

forestwork/main/models.py
from django.db import models

# Create your models here.

forestwork/main/views.py
from django.views.generic import TemplateView
from django.views.generic.edit import FormMixin
from jobs.models import Job
from jobs.forms import JobSearchForm
from users.models import User


# Create your views here.
class IndexView(FormMixin, TemplateView):
    template_name = 'main/index.html'
    form_class = JobSearchForm
    extra_context = {
        'title': 'ForestWork',
        'subtitle': 'Сервис поиска работы и кандидатов'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job_list'] = Job.objects.filter(status=1)[:5]
        context['employer_list'] = User.objects.filter(type=1)[:5]
        context['developer_list'] = User.objects.filter(type=0)[:5]
        context['job_count'] = Job.objects.all().count()
        return context

forestwork/templates/main/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<section id="home">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-7">
                <h1>ForestWork</h1>
                <div class="subtitle text-muted mb-3">Сервис поиска работы и кандидатов</div>
                <form method="GET" action="{% url 'jobs' %}" class="mb-3">
                    <div class="input-group">
                        {{ form.query }}
                        <button type="submit" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-search"></i>Поиск</button>
                    </div>
                </form>
                <div class="text-muted mb-5">Более {{ job_count }} вакансий дотупны к просмотру. Найдите свою новую работу уже сегодня.</div>
                <div class="d-flex">
                    {% if user.is_authenticated and user.type == 1 %}
                    <a href="{% url 'job_add' %}" class="btn btn-primary btn-with-icon" style="margin-right: 20px"><i class="fi fi-rr-add"></i>Добавить вакансию</a>
                    {% endif %}
                    <a href="{% url 'jobs' %}" class="btn btn-with-icon"><i class="fi fi-rr-briefcase"></i>Смотреть вакансии</a>
                </div>
            </div>
        <div class="col-lg-5 d-none d-lg-block">
            <img style="width: 100%" src="{% static 'img/home_image.png' %}" alt="">
        </div>
        </div>
    </div>
</section>
<section id="features">
    <div class="container">
        <div class="section-heading">
            <h2>Создайте профиль и начните поиск работы</h2>
            <div class="subtitle text-muted">Несколько преимуществ нашего сервиса по поиску работы</div>
        </div>
        <div class="card">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="card-featured">
                        <i class="fi fi-rr-briefcase"></i>
                        <div class="title">Работодатели сами предлагают работу</div>
                        <div class="text-muted">Работодатели видят ваш профиль на сайте и могут сами связываться с вами и
                            предложить работу.
                        </div>
                    </div>
                    <div class="card-featured">
                        <i class="fi fi-rr-form"></i>
                        <div class="title">Все контакты в одном месте</div>
                        <div class="text-muted">Не важно, работодатель вы или разработчик, смотрите контакты потенциальных
                            партнеров на страницах профиля
                        </div>
                    </div>
                    <div class="card-featured">
                        <i class="fi fi-rr-envelope"></i>
                        <div class="title">Не ждите ответа</div>
                        <div class="text-muted">
                            Благодаря возможности создавать неограниченое количество диалогов,
                            не останавливайтесь на одной вакансии.
                        </div>
                    </div>
                    <div>
                        {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-user"></i>Мой профиль</a>
                        {% else %}
                        <a href="{% url 'signup' %}" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-user"></i>Начать регистрацию</a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="{% static 'img/features_image.png' %}">
                </div>
            </div>
        </div>
    </div>
</section>
<section id='jobs'>
    <div class="container">
        <div class="section-heading">
            <h2>Недавно опубликованные вакансии</h2>
            <div class="subtitle text-muted">Возможно именно эти вакансии подарят вам работу всей жизни и сделают понедельники счастливым</div>
            <div class="btns">
                <a href="{% url 'employers' %}" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-briefcase"></i>Все вакансии</a>
            </div>
        </div>
        <div class="row">
            {% for job in job_list %}
                <div class="col-lg-6">
                    <div class="card card-border card-job">
                        <h2><a href="{% url 'job' pk=job.id %}">{{ job.title }}</a></h2>
                        <div class="salary">{{ job.salary }}$</div>
                        <div class="description mb-3">{{ job.description | truncatewords:20 }}</div>
                        <div class="subinfo text-bold text-muted d-flex flex-wrap">
                            <div class="text-icon">
                            <i class="fi fi-rr-marker"></i>
                            {% if not job.country and not job.city %}
                                Не указано
                            {% else %}
                                {{ job.country }} {{ job.city }}
                            {% endif %}
                            </div>
                            <div class="date_publish text-icon"><i class="fi fi-rr-calendar"></i>{{ job.date_publish }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
<section id='employers'>
    <div class="container">
        <div class="section-heading">
            <h2>Новые компании и работодатели на ForestWork</h2>
            <div class="subtitle text-muted">Найди команду, которая подходит тебя по ценностям, культурой и профессиональным целям</div>
            <div class="btns">
                <a href="{% url 'employers' %}" class="btn btn-primary btn-with-icon"><i class="fi fi-rr-user"></i>Все компании</a>
            </div>
        </div>
        <div class="row">
            {% for user in employer_list %}
            <div class="col-lg-6">
                <div class="card card-user">
                    <div class="avatar avatar-mini">{{ user.username|slice:"2" }}</div>
                    <h2><a href="{% url 'employer' pk=user.id %}">{{ user.name }}</a></h2>
                    <div class="subinfo text-muted d-flex flex-wrap">
                        <div class="text-bold text-icon">
                            <i class="fi fi-rr-marker"></i>
                            {% if not user.country and not user.city %}
                                Не указано
                            {% else %}
                                {{ user.country }} {{ user.city }}
                            {% endif %}
                        </div>
                        {% if user.job_set.count > 0 %}
                        <div class="text-bold text-icon">
                            <i class="fi fi-rr-e-learning"></i>
                            Опубликованных вакансий: {{ user.job_set.count }}
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<section id='developers'>
    <div class="container">
        <div class="section-heading">
            <h2>Новые кандидаты</h2>
             <div class="subtitle text-muted">Ищите и иследуйте кандидатов со всего мира</div>
            <div class="btns">
                <a href="{% url 'employers' %}" class="btn btn-primary">Все кандидаты</a>
            </div>
        </div>
        <div class="row">
            {% for user in developer_list %}
            <div class="col-lg-6">
                <div class="card card-user">
                    <div class="avatar avatar-mini">{{ user.username|slice:"2" }}</div>
                    <h2><a href="{% url 'employer' pk=user.id %}">{{ user.name }}</a></h2>
                    <div class="subinfo text-muted d-flex flex-wrap">
                        <div class="text-bold text-icon">
                            <i class="fi fi-rr-marker"></i>
                            {% if not user.country and not user.city %}
                                Не указано
                            {% else %}
                                {{ user.country }} {{ user.city }}
                            {% endif %}
                        </div>
                        {% if user.exp %}
                        <div class="text-bold text-icon">
                            <i class="fi fi-rr-e-learning"></i>
                            Опыт работы: {{ user.get_exp_display }}
                        </div>
                        {% endif %}
                    </div>
                    {% if user.specialization %}
                    <div class="tags d-flex mt-2">
                        <span class="tag">{{ user.specialization }}</span>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}